[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/tmdb"
  to = "https://cinequeue-api.cinequeue.workers.dev/api/tmdb"
  status = 200
  force = true

[[redirects]]
  from = "/api/backend/*"
  to = "https://cinequeue-api.cinequeue.workers.dev/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
